from __future__ import annotations

import argparse
import csv
import json
import shutil
from pathlib import Path
from typing import Any

import numpy as np

from build_ct_acoustic_model import fit_power_law_params_multi


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def sample_inputs() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    case_id = 0
    for alpha_at_500 in (4.0, 6.35, 8.7):
        original_alpha0 = alpha_at_500 / 0.5
        for c0 in (1500.0, 2200.0, 3360.0):
            rows.append(
                {
                    "case_id": f"y2_{case_id:03d}",
                    "a0_db_mhz_y_cm": original_alpha0,
                    "y": 1.0,
                    "c0_m_s": c0,
                    "f_ref_hz": 500000.0,
                    "y_ref": 2.0,
                    "note": "079 skull alpha@500kHz converted from PRESTUS Mueller y=1 route",
                }
            )
            case_id += 1
    sensitivity = [
        ("sens_000", 0.6, 1.1, 1540.0, 500000.0, 1.5, "soft-tissue-like non-y2 sensitivity case"),
        ("sens_001", 8.0, 1.3, 2500.0, 500000.0, 2.2, "skull-like non-y2 sensitivity case"),
        ("sens_002", 13.3, 1.0, 2800.0, 650000.0, 1.5, "k-plan-like alpha with non-500kHz reference"),
    ]
    for case_id, a0, y, c0, f_ref, y_ref, note in sensitivity:
        rows.append(
            {
                "case_id": case_id,
                "a0_db_mhz_y_cm": a0,
                "y": y,
                "c0_m_s": c0,
                "f_ref_hz": f_ref,
                "y_ref": y_ref,
                "note": note,
            }
        )
    return rows


def python_expected(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for row in rows:
        value = float(
            fit_power_law_params_multi(
                np.array([float(row["a0_db_mhz_y_cm"])], dtype=np.float64),
                np.array([float(row["y"])], dtype=np.float64),
                np.array([float(row["c0_m_s"])], dtype=np.float64),
                float(row["f_ref_hz"]),
                float(row["y_ref"]),
            )[0]
        )
        item = dict(row)
        item["python_a0_fit_db_mhz_yref_cm"] = value
        out.append(item)
    return out


def matlab_runner_text(prestus_medium_dir: str) -> str:
    return f"""% Auto-generated by prepare_fit_alpha_power_matlab_crosscheck.py
% This script compares PRESTUS fitPowerLawParamsMulti.m outputs against
% fus-sim Python expected values. It does not run k-Wave simulations.

clear; clc;

package_dir = fileparts(mfilename('fullpath'));
prestus_medium_dir = '{prestus_medium_dir.replace("\\", "/")}';
addpath(package_dir);
addpath(prestus_medium_dir);

input_file = fullfile(package_dir, 'input_fixture.csv');
output_file = fullfile(package_dir, 'matlab_outputs.csv');

T = readtable(input_file, 'TextType', 'string');
n = height(T);
a0_fit = zeros(n, 1);

for idx = 1:n
    a0_fit(idx) = fitPowerLawParamsMulti( ...
        T.a0_db_mhz_y_cm(idx), ...
        T.y(idx), ...
        T.c0_m_s(idx), ...
        T.f_ref_hz(idx), ...
        T.y_ref(idx), ...
        false);
end

Out = table(T.case_id, a0_fit, 'VariableNames', {{'case_id', 'matlab_a0_fit_db_mhz_yref_cm'}});
writetable(Out, output_file);
disp(['Wrote ', output_file]);
"""


def helper_db2neper_text() -> str:
    return """function alpha_np = db2neper(alpha_db, y)
% Local helper for cross-check package.
% Converts dB/(MHz^y cm) to Np/((rad/s)^y m), matching k-Wave helper semantics.
alpha_np = alpha_db .* (log(10) ./ 20) .* 100 ./ ((2 .* pi .* 1e6) .^ y);
end
"""


def helper_neper2db_text() -> str:
    return """function alpha_db = neper2db(alpha_np, y)
% Local helper for cross-check package.
% Converts Np/((rad/s)^y m) to dB/(MHz^y cm), matching k-Wave helper semantics.
alpha_db = alpha_np ./ (log(10) ./ 20) ./ 100 .* ((2 .* pi .* 1e6) .^ y);
end
"""


def compare_if_available(expected_rows: list[dict[str, Any]], matlab_results: Path | None) -> dict[str, Any] | None:
    if matlab_results is None or not matlab_results.exists():
        return None
    with matlab_results.open("r", encoding="utf-8-sig", newline="") as handle:
        matlab_rows = list(csv.DictReader(handle))
    matlab_by_id = {row["case_id"]: float(row["matlab_a0_fit_db_mhz_yref_cm"]) for row in matlab_rows}
    comparisons = []
    for row in expected_rows:
        case_id = str(row["case_id"])
        py = float(row["python_a0_fit_db_mhz_yref_cm"])
        ma = matlab_by_id[case_id]
        abs_err = abs(ma - py)
        rel_err = abs_err / max(abs(py), 1e-12)
        comparisons.append(
            {
                "case_id": case_id,
                "python": py,
                "matlab": ma,
                "abs_error": abs_err,
                "rel_error": rel_err,
            }
        )
    return {
        "matlab_results_path": str(matlab_results),
        "case_count": len(comparisons),
        "max_abs_error": max(row["abs_error"] for row in comparisons),
        "max_rel_error": max(row["rel_error"] for row in comparisons),
        "tolerance_abs": 1e-9,
        "tolerance_rel": 1e-9,
        "passed": all(row["abs_error"] <= 1e-9 or row["rel_error"] <= 1e-9 for row in comparisons),
        "comparisons": comparisons,
    }


def report_text(summary: dict[str, Any]) -> str:
    matlab_status = "可用" if summary["matlab_available"] else "未发现"
    executed = "已导入并比较" if summary["matlab_executed"] else "未执行"
    return f"""# PRESTUS fitPowerLawParamsMulti MATLAB/Python 交叉测试包

## 结论

- 本机 MATLAB：{matlab_status}
- MATLAB 交叉测试：{executed}
- 本阶段没有运行 k-Wave，没有重建 CT 模型，没有生成 pressure field。

## 输出

- 输入 fixture：`input_fixture.csv`
- Python 期望输出：`python_expected_outputs.csv`
- MATLAB runner：`run_fit_alpha_crosscheck.m`
- MATLAB helper：`db2neper.m`、`neper2db.m`
- 机器可读摘要：`crosscheck_summary.json`

## 使用方式

在有 MATLAB 的环境中，进入本目录后运行：

```matlab
run_fit_alpha_crosscheck
```

运行后会生成：

```text
matlab_outputs.csv
```

之后可把 `matlab_outputs.csv` 放回本目录，再用本脚本的 `--matlab-results` 选项进行误差比较。

## 解释边界

- 该交叉测试只验证 PRESTUS MATLAB 函数和 fus-sim Python 函数在选定样本上的数值一致性。
- 即使通过，也不能解除 `prestus_fit_alpha_power_2` 的 pressure block。
- pressure sanity run 仍需要单独 evidence brief、dry-run quality 和用户明确授权。
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare MATLAB/Python cross-check package for fitPowerLawParamsMulti.")
    parser.add_argument("--output-dir", default="outputs/fit_alpha_power_matlab_crosscheck")
    parser.add_argument(
        "--prestus-medium-dir",
        default="data/source_code_refs/PRESTUS_source/functions/medium",
    )
    parser.add_argument("--matlab-results", default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    prestus_medium_dir = Path(args.prestus_medium_dir)

    inputs = sample_inputs()
    expected = python_expected(inputs)
    write_csv(output_dir / "input_fixture.csv", inputs)
    write_csv(output_dir / "python_expected_outputs.csv", expected)
    write_json(output_dir / "python_expected_outputs.json", {"rows": expected})

    (output_dir / "run_fit_alpha_crosscheck.m").write_text(
        matlab_runner_text(str(prestus_medium_dir.resolve())),
        encoding="utf-8",
    )
    (output_dir / "db2neper.m").write_text(helper_db2neper_text(), encoding="utf-8")
    (output_dir / "neper2db.m").write_text(helper_neper2db_text(), encoding="utf-8")

    matlab_path = shutil.which("matlab")
    matlab_results = Path(args.matlab_results) if args.matlab_results else None
    comparison = compare_if_available(expected, matlab_results)

    summary = {
        "scope": "MATLAB/Python numerical cross-check package only; no k-Wave and no pressure simulation",
        "matlab_available": matlab_path is not None,
        "matlab_path": matlab_path,
        "matlab_executed": comparison is not None,
        "prestus_medium_dir": str(prestus_medium_dir),
        "case_count": len(inputs),
        "outputs": {
            "input_fixture_csv": str(output_dir / "input_fixture.csv"),
            "python_expected_outputs_csv": str(output_dir / "python_expected_outputs.csv"),
            "matlab_runner": str(output_dir / "run_fit_alpha_crosscheck.m"),
            "db2neper_helper": str(output_dir / "db2neper.m"),
            "neper2db_helper": str(output_dir / "neper2db.m"),
        },
        "comparison": comparison,
        "pressure_simulation_allowed": False,
        "recommended_next_step": "Run run_fit_alpha_crosscheck.m in MATLAB if available, then import matlab_outputs.csv for comparison.",
    }
    write_json(output_dir / "crosscheck_summary.json", summary)
    (output_dir / "crosscheck_report.md").write_text(report_text(summary), encoding="utf-8-sig")
    print(f"Wrote MATLAB/Python cross-check package to {output_dir}")


if __name__ == "__main__":
    main()
